### ISSUE TITLE
updated Libav.cpp file

### ISSUE THREAD

**Issue by Dual01** [AndreHro/ohPlayer#1]
I read that you obviously corrected some bugs in the Libav.cpp file of openhome player but I cannot find an updated version. I get always an error code obviously related to a bug in the Libav.cpp file when I add the USE_LIBAVCODEC=1 option to include the native codecs. Did it work wth the updated file?
It would be great to get some hint.
Thanks

**Comment by AndreHro** [comment]
I changed some Interfaces in Libav.cpp, but I think they are now included in the new original version of openhome. 
I stoped using the USE_LIBAVCODEC=1 because I observed instabilities in codec type recognition. 
In this branch the idea is to use a newer version of the dependencies.

**Comment by Dual01** [comment]
The problem is when I compile ohPlayer  with USE_LIBAVCODEC=1 in raspbian stretch, the compilation fails. It also fails with jessie. I pasted the compilation report in the original ohplayer repository. Thus, something seems to be wrong in the actual Libav.cpp.
Do you have any idea what could be the problem?

**Comment by AndreHro** [comment]
I start to modify Libav.cpp in order to compile using ubuntu arm. I will try to fix the deprecated warnings as well.

**Comment by AndreHro** [comment]
Hi, I committed a updated version of LIBAV. I test this with Ubuntu 20.04 and mp3 and m4a files. 
Using m4a files I observed that some files are not working. Converting them using ffmpeg -I infile.m4a  -codec copy -map 0 -movflags faststart outfile.m4a they are working too, see https://forums.slimdevices.com/showthread.php?110011-Squeezelite-Picoreplayer-not-playing-a-lot-of-ALAC-files&p=931167&viewfull=1#post931167

**Comment by Dual01** [comment]
Thanks, now, I get the following errors for raspian:

make raspbian DISABLE_GTK=1 USE_LIBAVCODEC=1
make -f Makefile.raspbian
make[1]: Entering directory '/home/pi/ohPlayer/linux'
g++ -c -Wall -std=c++0x -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -DTARG_ARCH=Linux-rpi -fstack-protector -fstack-check -DDEFINE_LITTLE_ENDIAN -DUSE_LIBAVCODEC -I../dependencies/Linux-rpi/ohMediaPlayer/include -I../dependencies/Linux-rpi/ohNetmon/include -I../dependencies/Linux-rpi/openssl/include -I../dependencies/Linux-rpi/ohNetGenerated-Linux-rpi-Release/include/ohnet/OpenHome/Net/Core -I../dependencies/Linux-rpi/ohNet-Linux-rpi-Release/include/ohnet -c ControlPointProxy.cpp -o raspbian/objs/ControlPointProxy.o
ControlPointProxy.cpp:688:6: error: prototype for ‘void OpenHome::Av::ControlPointProxy::CPUpnpAv::NotifyTrack(OpenHome::Media::Track&, OpenHome::TBool)’ does not match any in class ‘OpenHome::Av::ControlPointProxy::CPUpnpAv’
 void ControlPointProxy::CPUpnpAv::NotifyTrack(Media::Track& /*aTrack*/,
      ^
In file included from ControlPointProxy.cpp:23:0:
ControlPointProxy.h:141:18: error: candidate is: virtual void OpenHome::Av::ControlPointProxy::CPUpnpAv::NotifyTrack(OpenHome::Media::Track&, const OpenHome::Brx&, OpenHome::TBool)
             void NotifyTrack(Media::Track& aTrack, const Brx& aMode,
                  ^
ControlPointProxy.h:115:11: error: ‘class OpenHome::Av::ControlPointProxy::CPUpnpAv’ is private
     class CPUpnpAv : private Media::IPipelineObserver
           ^
ControlPointProxy.cpp:688:6: error: within this context
 void ControlPointProxy::CPUpnpAv::NotifyTrack(Media::Track& /*aTrack*/,
      ^
ControlPointProxy.cpp:697:6: error: prototype for ‘void OpenHome::Av::ControlPointProxy::CPUpnpAv::NotifyTime(OpenHome::TUint)’ does not match any in class ‘OpenHome::Av::ControlPointProxy::CPUpnpAv’
 void ControlPointProxy::CPUpnpAv::NotifyTime(TUint /*aSeconds*/)
      ^
In file included from ControlPointProxy.cpp:23:0:
ControlPointProxy.h:144:18: error: candidate is: virtual void OpenHome::Av::ControlPointProxy::CPUpnpAv::NotifyTime(OpenHome::TUint, OpenHome::TUint)
             void NotifyTime(TUint aSeconds,
                  ^
ControlPointProxy.h:115:11: error: ‘class OpenHome::Av::ControlPointProxy::CPUpnpAv’ is private
     class CPUpnpAv : private Media::IPipelineObserver
           ^
ControlPointProxy.cpp:697:6: error: within this context
 void ControlPointProxy::CPUpnpAv::NotifyTime(TUint /*aSeconds*/)
      ^
Makefile.raspbian:115: recipe for target 'raspbian/objs/ControlPointProxy.o' failed
make[1]: *** [raspbian/objs/ControlPointProxy.o] Error 1
make[1]: Leaving directory '/home/pi/ohPlayer/linux'
Makefile:28: recipe for target 'raspbian' failed
make: *** [raspbian] Error 2

**Comment by AndreHro** [comment]
The problem is that newer versions of ohMedia have different interfaces. 
Which version of dependencies are you using? They are defined in projectdata/dependencies.json. And could you please delete the dependencies directory and 
use ./go fetch --all again?

**Comment by Dual01** [comment]
I got it running with the new Libav.cpp and makefile.raspian which were updated by you and the "original" other files from the openhome repository (Volume.cpp, ExampleMediaPlayer.h, ExampleMediaPlayer.cpp and ControlPointProxy.cpp). 
Here is the dependency.json file I used:
 {   "name": "ohNet",
        "type": "openhome",
        "platform-specific": true,
        "version": "1.22.3172",
        "archive-suffix": "-${debugmode}",
        "main-dir": "${dest}${name}-${platform}-${debugmode}",
        "configure-args": [
            "--ohnet-lib-dir", "${main-dir}/lib",
            "--ohnet-include-dir", "${main-dir}/include/ohnet"
        ],
        "source-git": "https://github.com/openhome/ohNet.git"
    },
    {   "name": "ohWafHelpers",
        "type": "openhome",
        "platform-specific": false,
        "version": "0.1.117",
        "cross-check": false,
        "archive-filename": "${name}-${version}.tar.gz",
        "source-git": "https://github.com/openhome/ohWafHelpers.git"
.......

**Comment by Dual01** [comment]
When I use your go file and the ./go fetch --all  command, I get the follwing errors : failed to fetch some dependencies: ohMediaPlayer ohNet

Fetching 'ohMediaPlayer'
  from AWS s3://linn-artifacts-public/artifacts/ohMediaPlayer/ohMediaPlayer-1.123.893-Linux-rpi-Release.tar.gz
  from 'https://s3-eu-west-1.amazonaws.com/linn-artifacts-public/artifacts/ohMediaPlayer/ohMediaPlayer-1.123.893-Linux-rpi-Release.tar.gz'
  **** WARNING - failed to fetch ohMediaPlayer-1.123.893-Linux-rpi-Release.tar.gz ****

Fetching 'ohNet'
  from AWS s3://linn-artifacts-public/artifacts/ohNet/ohNet-1.29.3800-Linux-rpi-Release.tar.gz
  from 'https://s3-eu-west-1.amazonaws.com/linn-artifacts-public/artifacts/ohNet/ohNet-1.29.3800-Linux-rpi-Release.tar.gz'
  **** WARNING - failed to fetch ohNet-1.29.3800-Linux-rpi-Release.tar.gz ****

Fetching 'ohWafHelpers'
  from AWS s3://linn-artifacts-public/artifacts/ohWafHelpers/ohWafHelpers-0.2.125.tar.gz
  from 'https://s3-eu-west-1.amazonaws.com/linn-artifacts-public/artifacts/ohWafHelpers/ohWafHelpers-0.2.125.tar.gz'
  unpacking to '/home/pi/ohPlayer/dependencies/AnyPlatform'
OK

Fetching 'openssl'
  from AWS s3://linn-artifacts-public/artifacts/openssl/openssl-0.3.92-Linux-rpi-Release.tar.bz2
  from 'https://s3-eu-west-1.amazonaws.com/linn-artifacts-public/artifacts/openssl/openssl-0.3.92-Linux-rpi-Release.tar.bz2'
  unpacking to '/home/pi/ohPlayer/dependencies/Linux-rpi'
OK

Fetching 'ohNetGenerated'
  from AWS s3://linn-artifacts-public/artifacts/ohNetGenerated/ohNetGenerated-1.1.180-Linux-rpi-Release.tar.gz
  from 'https://s3-eu-west-1.amazonaws.com/linn-artifacts-public/artifacts/ohNetGenerated/ohNetGenerated-1.1.180-Linux-rpi-Release.tar.gz'
  unpacking to '/home/pi/ohPlayer/dependencies/Linux-rpi'
OK
Failed to fetch some dependencies: ohMediaPlayer ohNet
Failed to load requested dependencies

**Comment by AndreHro** [comment]
Yes I observed this too.  I moved on my raspberry pi to the armh versions of the dependencies. 
So as I said the idea of behind the repository AndreHro/ohPlayer was to get newer dependencies and then starting to enable Airplay.  

Yesterday, I create AndreHro/ohPlayer-1 in order to pull the changes of Libav.cpp back into the master openhome repository. So AndreHro/ohPlayer-1 should work without problems and is equivalent to https://github.com/AndreHro/ohPlayer/issues/1#issuecomment-699487307

**Comment by Dual01** [comment]
Thanks for the hint, it works great with Linux-armhf.
Then, I have another ohplayer problem, maybe you can help: I cannot stream from Qobuz. Although I can add music files to the playlist, it starts playing and stops immediately. It plays files from my local Kazoo Server without problems. Do you have any idea what could be wrong?

**Comment by Dual01** [comment]
seems to be a problem with the app ID
